### ISSUE TITLE
Windows: Profile not deleted, after image folder selected

### ISSUE THREAD

**Issue by Maradonna90** [Maradonna90/NewGAN-Manager#1]
```
Starting Application
------------------------------------------------
Loading cfg.json
Loading current profile
Creating GUI
Created main box
Created prf_box
Created prf_inp
Updating generation label
Create new profile: test
switch profile: test
Refresh Input Buttons
Select Folder...
Delete profile: test
```

profile has to be reselected to get deletion working.

**Comment by Maradonna90** [comment]
```
Traceback (most recent call last):
  File "/home/marco/NewGAN-Manager/beeware-newgan/lib/python3.8/site-packages/toga_gtk/wid  gets/button.py", line 39, in gtk_on_press                                                   
    self.interface.on_press(self.interface)                                               l 
  File "/home/marco/NewGAN-Manager/beeware-newgan/lib/python3.8/site-packages/toga/handlers.py", line 55, in _handler
    result = handler(interface, *args, **kwargs)
  File "/home/marco/NewGAN-Manager/src/newganmanager/app.py", line 81, in <lambda>
    prfsel_btn = toga.Button(label="Delete", on_press=lambda e=None, c=self.prfsel_lst : self._delete_profile(c))
  File "/home/marco/NewGAN-Manager/src/newganmanager/app.py", line 244, in _delete_profile
    os.remove(self.prf_cfg['img_dir']+"config.xml")
FileNotFoundError: [Errno 2] No such file or directory: '/home/marco/FMNEWGAN-replacement-tool/config.xml'
Traceback (most recent call last):
  File "/home/marco/NewGAN-Manager/beeware-newgan/lib/python3.8/site-packages/toga_gtk/widgets/selection.py", line 17, in gtk_on_select
    self.interface.on_select(widget)
  File "/home/marco/NewGAN-Manager/beeware-newgan/lib/python3.8/site-packages/toga/handlers.py", line 55, in _handler
    result = handler(interface, *args, **kwargs)
  File "/home/marco/NewGAN-Manager/src/newganmanager/app.py", line 199, in _set_profile_status
    with open(self.prf_cfg['img_dir']+'config.xml', 'wb') as output, open('.config/'+name+'.xml', 'rb') as input:
FileNotFoundError: [Errno 2] No such file or directory: '.config/No Profile.xml'
```
