### ISSUE TITLE
App crashes on launch (macOS 12.1)

### ISSUE THREAD

**Issue by tkis** [Maradonna90/NewGAN-Manager#117]
**Description**
App crashes on launch 

**To Reproduce**
Self-explanatory

**Error log**
```
Traceback (most recent call last):
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/app.py", line 430, in main
    fh = logging.FileHandler('newgan.log')
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/newgan.log'
```

**Comment by Maradonna90** [comment]
duplicate #91
