### ISSUE TITLE
[BUG] Program does not open on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by ayoob-portfolio** [Maradonna90/NewGAN-Manager#122]
**Describe the bug**
Program does not open on Ubuntu 20.04.3 LTS

**To Reproduce**
1. Download ZIP
2. Extract and give executable permissions
3. Run

**Expected behavior**
Expected the program to run

**Screenshots**
![image](https://user-images.githubusercontent.com/87142880/154858802-e166501a-b4b7-45be-a6b0-d485480b1ff5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 using KDE Plasma DE

**Comment by cameronjlarsen** [comment]
Receiving same error trying to run AppImage on EndeavorOS

Screenshots
![NewGanError](https://user-images.githubusercontent.com/44081018/178825673-004abab2-3927-4ed2-a242-c9e86429b705.png)

**Comment by mdlsvensson** [comment]
Same here on endeavor, anyone got  it working?

**Comment by AnthonyMahe** [comment]
Same with Kubuntu 23.04

./NewGAN-Manager-1.3.1-x86_64.AppImage
/tmp/.mount_NewGAN9bCxAt/usr/app/xmlparser.py:9: DeprecationWarning: invalid escape sequence \/
  UID_regex = re.compile('([0-9]{7,}(?=\/))')
/tmp/.mount_NewGAN9bCxAt/usr/app/xmlparser.py:28: DeprecationWarning: invalid escape sequence \/
  UID_regex = re.compile('('+uid+'(?=\/))')
/tmp/.mount_NewGAN9bCxAt/usr/app/rtfparser.py:28: DeprecationWarning: invalid escape sequence \|
  rtf_regex = re.compile('(\|\s*[0-9]{8,}\s*)(\|\s*([A-Z]{3})*\s*)+(\|[\s*\w*\.*\-*]+)(\|[\s*\d+]+){3}\|')
Traceback (most recent call last):
  File "/tmp/.mount_NewGAN9bCxAt/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_NewGAN9bCxAt/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_NewGAN9bCxAt/usr/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "/tmp/.mount_NewGAN9bCxAt/usr/app/newganmanager/app.py", line 439, in main
    return NewGANManager()
  File "/tmp/.mount_NewGAN9bCxAt/usr/app/newganmanager/app.py", line 41, in __init__
    super().__init__()
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga/app.py", line 272, in __init__
    self.factory = get_platform_factory(factory)
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga/platform.py", line 41, in get_platform_factory
    from toga_gtk import factory
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/app.py", line 13, in <module>
    from .keys import gtk_accel
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/keys.py", line 3, in <module>
    from .libs import Gdk
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/libs/__init__.py", line 1, in <module>
    from .gtk import *  # noqa: F401, F403
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/libs/gtk.py", line 1, in <module>
    import gi
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
