### ISSUE TITLE
Mac Application Error

### ISSUE THREAD

**Issue by jgpeace92** [Maradonna90/NewGAN-Manager#126]
Getting the below error when opening the application on mac:

Traceback (most recent call last):
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/app.py", line 430, in main
    fh = logging.FileHandler('newgan.log')
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/newgan.log'

**Comment by jgpeace92** [comment]
Found the main error thread
