### ISSUE TITLE
[BUG] Application won't open on MBP 16 (Apple Silicon)

### ISSUE THREAD

**Issue by brankfrank** [Maradonna90/NewGAN-Manager#139]
Follow install directions.
Attempt to open application after giving it permission to open.
Message: The application “NewGAN-Manager” can’t be opened.

MacOS12.2

**Comment by Maradonna90** [comment]
try using Rosetta

**Comment by leewonnacott** [comment]
Heya! 

I've tried opening 1.3.1 with Rosseta and I'm seeing the below error:
`Traceback (most recent call last):
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "NewGAN-Manager.app/Contents/Resources/app_packages/toga/app.py", line 511, in main_loop
    self._impl.main_loop()
  File "NewGAN-Manager.app/Contents/Resources/app_packages/toga_cocoa/app.py", line 338, in main_loop
    self.create()
  File "NewGAN-Manager.app/Contents/Resources/app_packages/toga_cocoa/app.py", line 257, in create
    self.interface.startup()
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/app.py", line 53, in startup
    fh = logging.FileHandler(str(self.paths.app)+'/newgan.log')
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/private/var/folders/2k/8m1151z52knbsk4hnc0x9grr0000gn/T/AppTranslocation/085D4EC4-36A2-41CF-B4EC-842E80E3AD73/d/NewGAN-Manager.app/Contents/Resources/app/newganmanager/newgan.log'
`

Is this a known issue?

**Comment by schtocker** [comment]
Bumping as I also have this issue on an M1 Macbook Pro running MacOS 12.2.1

**Comment by Maradonna90** [comment]
can you open the app with admin rights? clearly an issue with permissions. Its not ideal.

**Comment by johancantona** [comment]
This doesnt work.. bump

**Comment by ulyanovvladimir** [comment]
I had the same issue. I've fixed it using Rosetta for the application. MacOS 12.1 , M1 Macbook Pro
