### ISSUE TITLE
Unable to install/run on Linux (Ubuntu)

### ISSUE THREAD

**Issue by APettit98** [Maradonna90/NewGAN-Manager#148]
I wanted to try using this on my Ubuntu system, but have been unable to get anything running. The instructions imply there should be a .AppImage file upon download, but I don't see any such file. I've also tried running app.py, but had issues installing the dependencies. I've wondered if maybe I'm not downloading it correctly or perhaps linux isn't actually supported. Any help would be much appreciated, thank you!

**Comment by Ricardeano** [comment]
Can't help with your issue, unfortunately but can confirm I am having exactly the same issue. I cannot see an appimage file in the download to make executable (on Manjaro for what it is worth). I feel like I might be missing something simple here as I am not familiar with appimages but online help seems to suggest there should be a .appimage file which I cannot find.

**Comment by sameerchandra** [comment]
@APettit98 @Ricardeano I hope you've downloaded the release and not the repo itself.

Here's the link to the latest release: https://github.com/Maradonna90/NewGAN-Manager/releases/download/v1.3.1/NewGAN-Manager-Installer-Linux-v1.3.1.zip

**Comment by Ricardeano** [comment]
> @APettit98 @Ricardeano I hope you've downloaded the release and not the repo itself.
> 
> Here's the link to the latest release: https://github.com/Maradonna90/NewGAN-Manager/releases/download/v1.3.1/NewGAN-Manager-Installer-Linux-v1.3.1.zip

Apparently that is exactly what I was doing! Thanks for responding - it's much appreciated!

**Comment by sunwhisper** [comment]
`
/tmp/.mount_NewGAN8tAeNE/usr/app/xmlparser.py:9: DeprecationWarning: invalid escape sequence \/
  UID_regex = re.compile('([0-9]{7,}(?=\/))')
/tmp/.mount_NewGAN8tAeNE/usr/app/xmlparser.py:28: DeprecationWarning: invalid escape sequence \/
  UID_regex = re.compile('('+uid+'(?=\/))')
/tmp/.mount_NewGAN8tAeNE/usr/app/rtfparser.py:28: DeprecationWarning: invalid escape sequence \|
  rtf_regex = re.compile('(\|\s*[0-9]{8,}\s*)(\|\s*([A-Z]{3})*\s*)+(\|[\s*\w*\.*\-*]+)(\|[\s*\d+]+){3}\|')
Traceback (most recent call last):
  File "/tmp/.mount_NewGAN8tAeNE/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_NewGAN8tAeNE/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_NewGAN8tAeNE/usr/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "/tmp/.mount_NewGAN8tAeNE/usr/app/newganmanager/app.py", line 439, in main
    return NewGANManager()
  File "/tmp/.mount_NewGAN8tAeNE/usr/app/newganmanager/app.py", line 41, in __init__
    super().__init__()
  File "/tmp/.mount_NewGAN8tAeNE/usr/app_packages/toga/app.py", line 272, in __init__
    self.factory = get_platform_factory(factory)
  File "/tmp/.mount_NewGAN8tAeNE/usr/app_packages/toga/platform.py", line 41, in get_platform_factory
    from toga_gtk import factory
  File "/tmp/.mount_NewGAN8tAeNE/usr/app_packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/tmp/.mount_NewGAN8tAeNE/usr/app_packages/toga_gtk/app.py", line 13, in <module>
    from .keys import gtk_accel
  File "/tmp/.mount_NewGAN8tAeNE/usr/app_packages/toga_gtk/keys.py", line 3, in <module>
    from .libs import Gdk
  File "/tmp/.mount_NewGAN8tAeNE/usr/app_packages/toga_gtk/libs/__init__.py", line 1, in <module>
    from .gtk import *  # noqa: F401, F403
  File "/tmp/.mount_NewGAN8tAeNE/usr/app_packages/toga_gtk/libs/gtk.py", line 1, in <module>
    import gi
  File "/tmp/.mount_NewGAN8tAeNE/usr/app_packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
`

Is what i get when i run the appimage on ubuntu 22

**Comment by Lds502** [comment]
I got this to run on arch linux.

I extracted the AppImage

./NewGAN-Manager-1.3.1-x86_64_a34ba454bd304ad0d66866f7fb7dab26.AppImage --appimage-extract

This creates a squashfs-root folder.

I deleted the following file:

"/squashfs-root/usr/lib/libgmodule-2.0.so.0"

Then running "/squashfs-root/AppRun" the application launches.

I was getting other errors when trying to run the AppImage after repackaging it, however.

I had to run the application without any themes applied otherwise I was getting GTK errors when trying to select the location of my facepack.

**Comment by AnthonyMahe** [comment]
same with kubuntu 23.04
./NewGAN-Manager-1.3.1-x86_64.AppImage
/tmp/.mount_NewGAN9bCxAt/usr/app/xmlparser.py:9: DeprecationWarning: invalid escape sequence \/
  UID_regex = re.compile('([0-9]{7,}(?=\/))')
/tmp/.mount_NewGAN9bCxAt/usr/app/xmlparser.py:28: DeprecationWarning: invalid escape sequence \/
  UID_regex = re.compile('('+uid+'(?=\/))')
/tmp/.mount_NewGAN9bCxAt/usr/app/rtfparser.py:28: DeprecationWarning: invalid escape sequence \|
  rtf_regex = re.compile('(\|\s*[0-9]{8,}\s*)(\|\s*([A-Z]{3})*\s*)+(\|[\s*\w*\.*\-*]+)(\|[\s*\d+]+){3}\|')
Traceback (most recent call last):
  File "/tmp/.mount_NewGAN9bCxAt/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_NewGAN9bCxAt/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_NewGAN9bCxAt/usr/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "/tmp/.mount_NewGAN9bCxAt/usr/app/newganmanager/app.py", line 439, in main
    return NewGANManager()
  File "/tmp/.mount_NewGAN9bCxAt/usr/app/newganmanager/app.py", line 41, in __init__
    super().__init__()
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga/app.py", line 272, in __init__
    self.factory = get_platform_factory(factory)
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga/platform.py", line 41, in get_platform_factory
    from toga_gtk import factory
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/app.py", line 13, in <module>
    from .keys import gtk_accel
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/keys.py", line 3, in <module>
    from .libs import Gdk
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/libs/__init__.py", line 1, in <module>
    from .gtk import *  # noqa: F401, F403
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/toga_gtk/libs/gtk.py", line 1, in <module>
    import gi
  File "/tmp/.mount_NewGAN9bCxAt/usr/app_packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full

**Comment by vgnmnky** [comment]
> I got this to run on arch linux.
> 
> I extracted the AppImage
> 
> ./NewGAN-Manager-1.3.1-x86_64_a34ba454bd304ad0d66866f7fb7dab26.AppImage --appimage-extract
> 
> This creates a squashfs-root folder.
> 
> I deleted the following file:
> 
> "/squashfs-root/usr/lib/libgmodule-2.0.so.0"
> 
> Then running "/squashfs-root/AppRun" the application launches.
> 
> I was getting other errors when trying to run the AppImage after repackaging it, however.
> 
> I had to run the application without any themes applied otherwise I was getting GTK errors when trying to select the location of my facepack.

Would you mind saying how you ran the application without themes please?

**Comment by bvellender** [comment]
> > I got this to run on arch linux.
> > I extracted the AppImage
> > ./NewGAN-Manager-1.3.1-x86_64_a34ba454bd304ad0d66866f7fb7dab26.AppImage --appimage-extract
> > This creates a squashfs-root folder.
> > I deleted the following file:
> > "/squashfs-root/usr/lib/libgmodule-2.0.so.0"
> > Then running "/squashfs-root/AppRun" the application launches.
> > I was getting other errors when trying to run the AppImage after repackaging it, however.
> > I had to run the application without any themes applied otherwise I was getting GTK errors when trying to select the location of my facepack.
> 
> Would you mind saying how you ran the application without themes please?

Hi did you ever work this out?

**Comment by nevemlaci** [comment]
> > > I got this to run on arch linux.
> > > I extracted the AppImage
> > > ./NewGAN-Manager-1.3.1-x86_64_a34ba454bd304ad0d66866f7fb7dab26.AppImage --appimage-extract
> > > This creates a squashfs-root folder.
> > > I deleted the following file:
> > > "/squashfs-root/usr/lib/libgmodule-2.0.so.0"
> > > Then running "/squashfs-root/AppRun" the application launches.
> > > I was getting other errors when trying to run the AppImage after repackaging it, however.
> > > I had to run the application without any themes applied otherwise I was getting GTK errors when trying to select the location of my facepack.
> > 
> > 
> > Would you mind saying how you ran the application without themes please?
> 
> Hi did you ever work this out?

This solved the problem you are a legend!
