### ISSUE TITLE
Cannot open App on Mac[BUG]

### ISSUE THREAD

**Issue by liamlongbottom** [Maradonna90/NewGAN-Manager#164]
App doesn't open. I get this unexpected error:

Traceback (most recent call last):
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "NewGAN-Manager.app/Contents/Resources/app_packages/toga/app.py", line 511, in main_loop
    self._impl.main_loop()
  File "NewGAN-Manager.app/Contents/Resources/app_packages/toga_cocoa/app.py", line 338, in main_loop
    self.create()
  File "NewGAN-Manager.app/Contents/Resources/app_packages/toga_cocoa/app.py", line 257, in create
    self.interface.startup()
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/app.py", line 53, in startup
    fh = logging.FileHandler(str(self.paths.app)+'/newgan.log')
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/private/var/folders/wv/zns0mtwx4_n_m9lghvm21q040000gn/T/AppTranslocation/82F1C83A-6FDD-4588-A6EC-A2374AC79409/d/NewGAN-Manager.app/Contents/Resources/app/newganmanager/newgan.log'

**Comment by Maradonna90** [comment]
open with rosetta, otherwise no idea.
