### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nicketc99** [Maradonna90/NewGAN-Manager#170]
Installed v1.3.2, after deleting previous files - when launching app the app crashes with bellow error message
<img width="252" alt="image" src="https://github.com/Maradonna90/NewGAN-Manager/assets/133097504/c02e4eb3-b344-4722-ad02-e767c69b9af7">
log:
[newganmanager.log](https://github.com/Maradonna90/NewGAN-Manager/files/11439632/newganmanager.log)

**Comment by Aere1985** [comment]
Getting the same, Windows 11 in case that is relevant;

When installed for current user;

Traceback (most recent call last):
  File "\app\newganmanager\__main__.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 563, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 260, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 235, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 126, in create
    self.interface.startup()
  File "\app\newganmanager\app.py", line 124, in startup
    prfsel_btn = toga.Button(label="Delete", on_press=lambda e=None, c=self.prfsel_lst : self._delete_profile(c))
TypeError: __init__() got an unexpected keyword argument 'label'


When installed for all users;

Traceback (most recent call last):
  File "\app\newganmanager\__main__.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 563, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 260, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 235, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 126, in create
    self.interface.startup()
  File "\app\newganmanager\app.py", line 53, in startup
    fh = logging.FileHandler(str(self.paths.app)+'/newgan.log')
  File "logging\__init__.py", line 1147, in __init__
  File "logging\__init__.py", line 1176, in _open
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Maradonna (gestalt)\\NewGAN-Manager\\app\\newganmanager\\newgan.log'

The 2nd error occurs even if NewGan is run as administrator.

**Comment by Maradonna90** [comment]
thanks guys. I will mark it as a pre-release for now.

**Comment by jonapoul** [comment]
Same here on Windows 10.

**Comment by qadsawee79** [comment]
Same here

**Comment by Nii-Lamptey** [comment]
yup, 1.3.2 gave me the same crash message

Traceback (most recent call last):
  File "\app\newganmanager\__main__.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 563, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 260, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 235, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 126, in create
    self.interface.startup()
  File "\app\newganmanager\app.py", line 124, in startup
    prfsel_btn = toga.Button(label="Delete", on_press=lambda e=None, c=self.prfsel_lst : self._delete_profile(c))
TypeError: __init__() got an unexpected keyword argument 'label'

**Comment by wieg3hts** [comment]
Same for me. Any update here what to do to solve the problem?

**Comment by Maradonna90** [comment]
should be fixed with pinning versions.
