### ISSUE TITLE
crashing on windows

### ISSUE THREAD

**Issue by johnrout06** [Maradonna90/NewGAN-Manager#175]
everytime i try and open it it crashes. ive turn off my firewalls because i heard they stop things but it doesn't work. anyone know the fix? it says this btw
Traceback (most recent call last):
  File "\app\newganmanager\__main__.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 563, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 260, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 235, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 126, in create
    self.interface.startup()
  File "\app\newganmanager\app.py", line 124, in startup
    prfsel_btn = toga.Button(label="Delete", on_press=lambda e=None, c=self.prfsel_lst : self._delete_profile(c))
TypeError: __init__() got an unexpected keyword argument 'label'

**Comment by Ayal1** [comment]
duplicate of #170
