### ISSUE TITLE
RTF File selection dialog not showing up

### ISSUE THREAD

**Issue by Maradonna90** [Maradonna90/NewGAN-Manager#2]
```
Starting Application
------------------------------------------------
Loading cfg.json
Loading current profile
Creating GUI
Created main box
Created prf_box
Created prf_inp
Updating generation label
Create new profile: test
switch profile: test
Refresh Input Buttons
Select File...
```

**Comment by Maradonna90** [comment]
```
Starting Application
------------------------------------------------
Loading cfg.json
Loading current profile
Creating GUI
Created main box
Created prf_box
Created prf_inp
Updating generation label
Create new profile: test
switch profile: test
Refresh Input Buttons
Select File...
Fatal error in main loop
Traceback (most recent call last):
  File "C:\Users\grazyna\AppData\Local\Programs\NewGAN Manager\\app\newganmanager\app.py", line 301, in action_open_file_dialog
    file_types=['rtf']
  File "C:\Users\grazyna\AppData\Local\Programs\NewGAN Manager\\app_packages\toga\window.py", line 282, in open_file_dialog
    return self._impl.open_file_dialog(title, initial_directory, file_types, multiselect)
  File "C:\Users\grazyna\AppData\Local\Programs\NewGAN Manager\\app_packages\toga_winforms\window.py", line 182, in open_file_dialog
    "|All files (*.*)|*.*"
System.ArgumentException: Die angegebene Filterzeichenfolge ist ungültig. Sie muss eine Beschreibung des Filters gefolgt von einem vertikalen Strich (|) und dem Filtermuster enthalten. Die Zeichenfolgen für andere Filteroptionen müssen ebenfalls durch einen vertikalen Strich getrennt werden. Beispiel: "Textdateien (*.txt)|*.txt|Alle Dateien (*.*)|*.*".
   bei System.Windows.Forms.FileDialog.set_Filter(String value)
```

**Comment by Maradonna90** [comment]
related: https://github.com/beeware/toga/blob/8981790e2ece8c7104150ec073a540c1e0a65f46/src/winforms/toga_winforms/window.py

**Comment by Maradonna90** [comment]
fixed with new toga build
