### ISSUE TITLE
App crashing while opening

### ISSUE THREAD

**Issue by Caideco** [Maradonna90/NewGAN-Manager#206]
I used this earlier and it worked fine, now that im trying to make a new batch of faces the app crashes and the config file is missing, this is really detrimental to my save and has caused all the faces to be lost. how do i fix this

![image](https://github.com/Maradonna90/NewGAN-Manager/assets/89319017/f1737a38-faad-4a58-92b5-681c48c223e8)

**Comment by Ayal1** [comment]
Assuming this on v1.4.0 then try running the app as administrator

**Comment by JoeTin23** [comment]
having same issue even when running admin

**Comment by Ayal1** [comment]
Did you install for all users or just for your user?

**Comment by rogeriofza** [comment]
Same have the same issue...

Traceback (most recent call last):
  File "\app\newganmanager\__main__.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 663, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 285, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 258, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 113, in create
    self.interface._startup()
  File "\app_packages\toga\app.py", line 624, in _startup
    self.startup()
  File "\app\newganmanager\app.py", line 62, in startup
    self.profile_manager = Profile_Manager(Config_Manager().get_latest_prf(str(self.paths.app)+"/.user/cfg.json"), str(self.paths.app))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\app\profile_manager.py", line 10, in __init__
    self.prf_cfg = self.load_config(root_dir+"/.user/"+name+".json")
                                    ~~~~~~~~~~~~~~~~~~^~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by JCB1308** [comment]
Reinstall it but for all users and then run as admin

**Comment by rogeriofza** [comment]
We have tried that. It works for a while then starts reporting this error again.

**Comment by billybale** [comment]
yo i have the same issue. Did you find the solution?

**Comment by L4ndu28** [comment]
idk if u all alr resolved this, i was having the same issue... I removed the folder ( Maradonna (gestalt) ) and the NewGAN-Manager folder. Downloaded again and now i dont have any problem. I hope i helped someone

**Comment by billybale** [comment]
have done it but not working too. thanks for the suggestion
