### ISSUE TITLE
[BUG] App won't Launch & Won't input faces in FM24

### ISSUE THREAD

**Issue by mertun123** [Maradonna90/NewGAN-Manager#212]
After installing FM24 i had a problem with the faces not appearing in the game and after some trial and error i decided to reinstall newgan and now it wont launch at all i just get hit with

Traceback (most recent call last):
  File "\app\newganmanager\__main__.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 663, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 285, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 258, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 113, in create
    self.interface._startup()
  File "\app_packages\toga\app.py", line 624, in _startup
    self.startup()
  File "\app\newganmanager\app.py", line 62, in startup
    self.profile_manager = Profile_Manager(Config_Manager().get_latest_prf(str(self.paths.app)+"/.user/cfg.json"), str(self.paths.app))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\app\profile_manager.py", line 10, in __init__
    self.prf_cfg = self.load_config(root_dir+"/.user/"+name+".json")
                                    ~~~~~~~~~~~~~~~~~~^~~~~
TypeError: can only concatenate str (not "NoneType") to str

This happens on Windows 11

**Comment by Evil-Muffin9** [comment]
I ran into this problem what i had to do was uninstall the program then manually delete the folder in the following locations:

Folder to delete is **Maradonna (gestalt)**

C:\Users\USERNAME\AppData\Local\Maradonna (gestalt)
C:\Program Files\Maradonna (gestalt)\NewGAN-Manager

Once i removed all files i then installed the NewGAN Manager > right click on the NewGAN Manager.exe > Properties > Compatability > Run as Administrator > Apply/OK

If the above didn't work try uninstall again restart PC but the above worked for me at least.

**Comment by timupopo** [comment]
Copy → C:\Users\USERNAME\AppData\Local\Programs\NewGAN-Manager
Paste to → C:\Users\USERNAME\AppData\Local\Maradonna (gestalt)

I did this and the app worked!

**Comment by JCB1308** [comment]
Reinstall it for all users and run it as admin
