### ISSUE TITLE
App crashs when I try to start it

### ISSUE THREAD

**Issue by Ferdinand9999** [Maradonna90/NewGAN-Manager#244]
Traceback (most recent call last):
  File "\app\newganmanager\__main__.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 663, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 285, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 258, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 113, in create
    self.interface._startup()
  File "\app_packages\toga\app.py", line 624, in _startup
    self.startup()
  File "\app\newganmanager\app.py", line 62, in startup
    self.profile_manager = Profile_Manager(Config_Manager().get_latest_prf(str(self.paths.app)+"/.user/cfg.json"), str(self.paths.app))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\app\profile_manager.py", line 10, in __init__
    self.prf_cfg = self.load_config(root_dir+"/.user/"+name+".json")
                                    ~~~~~~~~~~~~~~~~~~^~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by tlebaxter** [comment]
Having the same error, any idea on how to fix this?

Update: This fixes itself if run as an administrator.

**Comment by Peranco** [comment]
From one start to another - Same here. Run as Admin did not solve the problem.  v1.4.0

**Comment by MudiLoodi** [comment]
> From one start to another - Same here. Run as Admin did not solve the problem. v1.4.0

- Go to the installation folder of NewGAN-manager. If on Windows it should be under "AppData\Local\Programs\Maradonna (gestalt)\NewGAN-Manager". 
- Go to app > newganmanager > .user
- open cfg.json and change "false" to "true" then save.

This fixed it for me.

**Comment by Peranco** [comment]
yep - worked for me. thx buddy

**Comment by testertesteb** [comment]
worked for me as well, only problem still left is that it does not generate files anymore. Its all set up correctly tho right? 

![Screenshot 2024-09-14 051225](https://github.com/user-attachments/assets/ea0b6a65-c40d-4c21-a162-67993f303fe8)
