### ISSUE TITLE
Macbook Pro - NewGAN fails to load

### ISSUE THREAD

**Issue by marthoe** [Maradonna90/NewGAN-Manager#98]
**Describe the bug**
I've installed newGAN manager, and gotten the search indexes completed (https://beta.fm-base.co.uk/articles/sagkrzealand-facepack/)I'm up to point 16 in the guide.

**To Reproduce**
1. Launch newGAN manager
2. Error appears immediately

**Expected behavior**
I've never seen it launch, but I expect it's meant to open the app for me to continue with setting up the facepacks.

**Screenshots**
<img width="630" alt="Screenshot 2021-12-11 at 06 55 23" src="https://user-images.githubusercontent.com/95955494/145667570-bf638bd8-c723-4f22-8d4f-7d1a7811d140.png">

**Desktop (please complete the following information):**
 - OS: iOS Monterey 12.0.1
 - Apple M1

**Attachments**
Add your `newgan.log` and RTF-FileTraceback (most recent call last):
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/app.py", line 430, in main
    fh = logging.FileHandler('newgan.log')
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/newgan.log'

Please let me know if you need more information, I'd love to get this working! :)

**Comment by Maradonna90** [comment]
duplicate

see #91
